from .employees.employee_list import employee_list
from .computers.computer_list import computer_list
from .computers.computers_form import computer_form
from .computers.computer_detail import computer_details
from .home import home
from .auth.logout import logout_user
from .training_programs.training_programs import training_program_list
from .training_programs.form import training_program_form
from .departments.department_list import department_list
from .departments.department_form import department_form
from .departments.department_detail import department_details
